### ISSUE TITLE
+3.3V and +3V3 nets in Silver Link "B" schematic

### ISSUE THREAD

**Issue by izero79** [queueRAM/ti_graph_link#3]
Hi,

I started to draw a pcb for the Silver Link B Rev 2 schematic and noticed that there is net for +3.3V and +3V3. I guess these should be the same net, or is there something that I didn't understand?

Do you have values for the lc filter caps, C9 & C10?

Also not related question, but do you have measurements for the original board? I could make the pcb so that it would fit in the original case (if someone would need that) if you can provide the dimensions as in the attached pic.

<img width="542" alt="dimensions" src="https://github.com/queueRAM/ti_graph_link/assets/2162749/23da78ff-3255-4921-a286-beae1cc89ae3">

**Comment by queueRAM** [comment]
Good catch on the +3.3V and +3V3. They are in fact supposed to be the same net and I'll change them all to +3V3

> Do you have values for the lc filter caps, C9 & C10?

I do not know C9 and C10 values since they are unlabeled and I'm not actually sure how to measure them in circuit. Any recommendations?

> Also not related question, but do you have measurements for the original board?

I just took these with a caliper. x&y are fairly precise, may want to use pixel dimensions of picture to confirm the rest
a = 2.45mm (0.096in) - difficult to measure
b = 1.11mm (0.043in) - difficult to measure, might be better to constrain with "x-(b+c)" below
c = 7.59mm (0.298in)
d = 2.13mm (0.084in) - assuming hole diameter
e = 24.72mm (0.973in) - difficult get hole center
x = 65.32mm (2.571in)
y = 18.24mm (0.718in)
x-(b+c) = 56.21mm (2.213in)

**Comment by izero79** [comment]
Thanks, can't say is there a reliable way to measure the caps in circuit. I need to study that what the values could be in that use case and try it out.

Measurements are more than precise enough. I will do a board drawing in near future and maybe I can make a pull request if you want to include that. Thank you again.
